### ISSUE TITLE
RubyとRailsのバージョンアップ対応

### ISSUE THREAD

**Issue by misaka3** [misaka3/flight_scoring#5]
サポートされているバージョンに変更する

**Comment by seita1996** [comment]
言い出しっぺなのでこのタスクもらいますね！
アサインしてください！

**Comment by misaka3** [comment]
@seita1996 
いまruby2.6.3にしてますがそれもEOLでした！
2.7もすぐ切れそうな気がするので3.0か3.1にあげてみたいなと思ってます！
![image](https://user-images.githubusercontent.com/59603784/183290587-dae8c0e5-1073-4356-8572-03bf8d3a30e7.png)


railsは6.1.6.1なのでいったん大丈夫そうですがあげてもらっても大丈夫です！
![image](https://user-images.githubusercontent.com/59603784/183290571-aa4edd86-09e1-452f-9626-6923eca18733.png)

**Comment by seita1996** [comment]
プルリク出しました～

https://github.com/misaka3/flight_scoring/pull/14
